/*
Resources and endpoints

When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.

At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.

The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.

Ruben Gamez
Founder, SignWell

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Additional files to be appended to the document. Will not replace existing files from the template. Document files can be uploaded by specifying a file URL or base64 string. Either `file_url` or `file_base64` must be present (not both). Valid file types are: .pdf, .docx, .jpg, .png, .ppt, .xls, .pages, and .txt.
 * @export
 * @interface AdditionalFilesMapInner
 */
export interface AdditionalFilesMapInner {
    /**
     * Name of the file that will be uploaded.
     * @type {string}
     * @memberof AdditionalFilesMapInner
     */
    'name': string;
    /**
     * Publicly available URL of the file to be uploaded.
     * @type {string}
     * @memberof AdditionalFilesMapInner
     */
    'file_url'?: string;
    /**
     * A RFC 4648 base64 string of the file to be uploaded.
     * @type {string}
     * @memberof AdditionalFilesMapInner
     */
    'file_base64'?: string;
}

