/*
Resources and endpoints

When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.

At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.

The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.

Ruben Gamez
Founder, SignWell

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateBulkSendRequest
 */
export interface CreateBulkSendRequest {
    /**
     * Unique identifiers for a list of templates.
     * @type {Array<string>}
     * @memberof CreateBulkSendRequest
     */
    'template_ids': Array<string>;
    /**
     * A RFC 4648 base64 string of the template CSV file to be validated.
     * @type {string}
     * @memberof CreateBulkSendRequest
     */
    'bulk_send_csv': string;
    /**
     * Whether to skip errors in the rows. Defaults to `false`.
     * @type {boolean}
     * @memberof CreateBulkSendRequest
     */
    'skip_row_errors'?: boolean;
    /**
     * Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings
     * @type {string}
     * @memberof CreateBulkSendRequest
     */
    'api_application_id'?: string;
    /**
     * The name of the Bulk Send. Will be used as the document name for each of the documents.
     * @type {string}
     * @memberof CreateBulkSendRequest
     */
    'name'?: string;
    /**
     * Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject.
     * @type {string}
     * @memberof CreateBulkSendRequest
     */
    'subject'?: string;
    /**
     * Email message for the signature request that recipients will see. Defaults to the default system message or a template message.
     * @type {string}
     * @memberof CreateBulkSendRequest
     */
    'message'?: string;
    /**
     * When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.
     * @type {boolean}
     * @memberof CreateBulkSendRequest
     */
    'apply_signing_order'?: boolean;
    /**
     * Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.
     * @type {string}
     * @memberof CreateBulkSendRequest
     */
    'custom_requester_name'?: string;
    /**
     * Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.
     * @type {string}
     * @memberof CreateBulkSendRequest
     */
    'custom_requester_email'?: string;
}

