/*
Resources and endpoints

When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.

At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.

The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.

Ruben Gamez
Founder, SignWell

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttachmentRequestsForTemplateMapInner } from './attachment-requests-for-template-map-inner';
import { CopiedPlaceholdersMapInner } from './copied-placeholders-map-inner';
import { FieldsForTemplateMapInnerInner } from './fields-for-template-map-inner-inner';
import { FilesMapInner } from './files-map-inner';
import { PlaceholdersMapInner } from './placeholders-map-inner';

/**
 * 
 * @export
 * @interface DocumentTemplateRequest
 */
export interface DocumentTemplateRequest {
    /**
     * 
     * @type {Array<FilesMapInner>}
     * @memberof DocumentTemplateRequest
     */
    'files': Array<FilesMapInner>;
    /**
     * The name of the template.
     * @type {string}
     * @memberof DocumentTemplateRequest
     */
    'name'?: string;
    /**
     * Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).
     * @type {string}
     * @memberof DocumentTemplateRequest
     */
    'subject'?: string;
    /**
     * Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).
     * @type {string}
     * @memberof DocumentTemplateRequest
     */
    'message'?: string;
    /**
     * Placeholders are generally job roles that must complete and/or sign the document. For example, a placeholder might be “Client” or “Legal Department”. When a document is created from the template, you assign a person to each placeholder.
     * @type {Array<PlaceholdersMapInner>}
     * @memberof DocumentTemplateRequest
     */
    'placeholders': Array<PlaceholdersMapInner>;
    /**
     * Copied placeholders are emailed the final document once it has been completed by all recipients.
     * @type {Array<CopiedPlaceholdersMapInner>}
     * @memberof DocumentTemplateRequest
     */
    'copied_placeholders'?: Array<CopiedPlaceholdersMapInner>;
    /**
     * Whether the template can still be updated before it is ready for usage. If set to `false` the template is marked as `Available` and it will be ready for use. Defaults to `false`.
     * @type {boolean}
     * @memberof DocumentTemplateRequest
     */
    'draft'?: boolean;
    /**
     * Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).
     * @type {number}
     * @memberof DocumentTemplateRequest
     */
    'expires_in'?: number;
    /**
     * Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.
     * @type {boolean}
     * @memberof DocumentTemplateRequest
     */
    'reminders'?: boolean;
    /**
     * When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.
     * @type {boolean}
     * @memberof DocumentTemplateRequest
     */
    'apply_signing_order'?: boolean;
    /**
     * Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings
     * @type {string}
     * @memberof DocumentTemplateRequest
     */
    'api_application_id'?: string;
    /**
     * An alternative way (if you can’t use the recommended way) of placing fields in specific locations of your document by using special text tags. Useful when changing the content of your files changes the location of fields. See API documentation for “Text Tags” for details. Defaults to false.
     * @type {boolean}
     * @memberof DocumentTemplateRequest
     */
    'text_tags'?: boolean;
    /**
     * A URL that recipients are redirected to after successfully signing a document.
     * @type {string}
     * @memberof DocumentTemplateRequest
     */
    'redirect_url'?: string;
    /**
     * Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.
     * @type {boolean}
     * @memberof DocumentTemplateRequest
     */
    'allow_decline'?: boolean;
    /**
     * In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.
     * @type {boolean}
     * @memberof DocumentTemplateRequest
     */
    'allow_reassign'?: boolean;
    /**
     * A URL that recipients are redirected to if the document is declined.
     * @type {string}
     * @memberof DocumentTemplateRequest
     */
    'decline_redirect_url'?: string;
    /**
     * Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.
     * @type {object}
     * @memberof DocumentTemplateRequest
     */
    'metadata'?: object;
    /**
     * Document fields placed on a document for collecting data or signatures from recipients. At least one field must be present in the Create Document request if `draft` is `false` (unless adding a signature page by using `with_signature_page`). Field data should be sent as a 2-dimensional JSON array. One array of fields is needed for each file in the files array. An array of fields can be empty if you have a file that does not contain any fields.
     * @type {Array<Array<FieldsForTemplateMapInnerInner>>}
     * @memberof DocumentTemplateRequest
     */
    'fields'?: Array<Array<FieldsForTemplateMapInnerInner>>;
    /**
     * Attachments that a recipient must upload to complete the signing process. Attachment requests are shown after all document fields have been completed.
     * @type {Array<AttachmentRequestsForTemplateMapInner>}
     * @memberof DocumentTemplateRequest
     */
    'attachment_requests'?: Array<AttachmentRequestsForTemplateMapInner>;
}

