/*
Resources and endpoints

When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.

At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.

The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.

Ruben Gamez
Founder, SignWell

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentRecipientsMapInner
 */
export interface DocumentRecipientsMapInner {
    /**
     * A unique identifier that you will give to each recipient. We recommend numbering sequentially from 1 to X. IDs are required for associating recipients to fields and more.
     * @type {string}
     * @memberof DocumentRecipientsMapInner
     */
    'id': string;
    /**
     * Name of the recipient.
     * @type {string}
     * @memberof DocumentRecipientsMapInner
     */
    'name'?: string;
    /**
     * Email address for the recipient.
     * @type {string}
     * @memberof DocumentRecipientsMapInner
     */
    'email': string;
    /**
     * If set, signers assigned with a passcode will be required to enter the passcode before they’re able to view and complete the document.
     * @type {string}
     * @memberof DocumentRecipientsMapInner
     */
    'passcode'?: string;
    /**
     * Email subject for the signature request that the recipient will see. Overrides the general subject for the document.
     * @type {string}
     * @memberof DocumentRecipientsMapInner
     */
    'subject'?: string;
    /**
     * Email message for the signature request that the recipient will see. Overrides the general message for the document.
     * @type {string}
     * @memberof DocumentRecipientsMapInner
     */
    'message'?: string;
    /**
     * Applies on when `embedded_signing` is `true`. By default, recipients are not notified through email to sign when doing embedded signing. Setting this to `true`  will send a notification email to the recipient. Default is `false`.
     * @type {boolean}
     * @memberof DocumentRecipientsMapInner
     */
    'send_email'?: boolean;
    /**
     * If `send_email` is `true` recipients will receive a new document notification immediately. In the case of embedded signing, you can delay this notification to only send if the document is not completed within a few minutes. The email notification will not go out if the document is completed before the delay time is over. Valid values are in minutes ranging from `0` to `60`. Defaults to `0`.
     * @type {number}
     * @memberof DocumentRecipientsMapInner
     */
    'send_email_delay'?: number;
}

