/*
Resources and endpoints

When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.

At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.

The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.

Ruben Gamez
Founder, SignWell

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentCreateNewDocumentResponseFieldsInnerInner
 */
export interface DocumentCreateNewDocumentResponseFieldsInnerInner {
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'api_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'height'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'required'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'value'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'width'?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'x'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'y'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'page'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'recipient_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'date_format'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'formula'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'lock_sign_date'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'fixed_width'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreateNewDocumentResponseFieldsInnerInner
     */
    'validation'?: string;
}

