/*
Resources and endpoints

When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.

At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.

The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.

Ruben Gamez
Founder, SignWell

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FieldsMapInnerInner
 */
export interface FieldsMapInnerInner {
    /**
     * Horizontal value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located.
     * @type {number}
     * @memberof FieldsMapInnerInner
     */
    'x': number;
    /**
     * Vertical value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located.
     * @type {number}
     * @memberof FieldsMapInnerInner
     */
    'y': number;
    /**
     * The page number within the file. If the page does not exist within the file then the field won\'t be created.
     * @type {number}
     * @memberof FieldsMapInnerInner
     */
    'page': number;
    /**
     * Unique identifier of the recipient assigned to the field. Recipients assigned to fields will be the only ones that will see and be able to complete those fields.
     * @type {string}
     * @memberof FieldsMapInnerInner
     */
    'recipient_id': string;
    /**
     * Field type of the field. Valid field types: initials, signatures, checkbox, date, and text. To autofill fields with contact data, use an autofill field type.
     * @type {string}
     * @memberof FieldsMapInnerInner
     */
    'type': FieldsMapInnerInnerTypeEnum;
    /**
     * Whether the field must be completed by the recipient. Defaults to `true` except for checkbox type fields.
     * @type {boolean}
     * @memberof FieldsMapInnerInner
     */
    'required'?: boolean;
    /**
     * Text and Date fields only: label that is displayed when the field is empty.
     * @type {string}
     * @memberof FieldsMapInnerInner
     */
    'label'?: string;
    /**
     * Varies according to the field type. Text fields accept strings or numbers. Date fields accept Iso8601 date strings. CheckBoxes accept booleans. Signature and Initials fields can\'t be signed through API requests. Autofill text fields accept strings or numbers.
     * @type {any}
     * @memberof FieldsMapInnerInner
     */
    'value'?: any;
    /**
     * Unique identifier of the field. Useful when needing to reference specific field values or update a document and its fields.
     * @type {string}
     * @memberof FieldsMapInnerInner
     */
    'api_id'?: string;
    /**
     * Text fields only: optional validation for field values. Valid values: numbers, letters, email_address, us_phone_number, us_zip_code, us_ssn, us_age, alphanumeric, us_bank_routing_number, us_bank_account.
     * @type {string}
     * @memberof FieldsMapInnerInner
     */
    'validation'?: FieldsMapInnerInnerValidationEnum;
    /**
     * Text fields only: whether the field width will stay fixed and text will display in multiple lines, rather than one long line. If set to `false` the field width will automatically grow horizontally to fit text on one line. Defaults to `false`.
     * @type {boolean}
     * @memberof FieldsMapInnerInner
     */
    'fixed_width'?: boolean;
    /**
     * Date fields only: makes fields readonly and automatically populates with the date the recipient signed. Defaults to `false`.
     * @type {boolean}
     * @memberof FieldsMapInnerInner
     */
    'lock_sign_date'?: boolean;
    /**
     * Date fields only: date format to use for the field. Valid values: MM/DD/YYYY, DD/MM/YYYY, YYYY/MM/DD, Month DD, YYYY, and MM/DD/YYYY hh:mm:ss a. Defaults to MM/DD/YYYY.
     * @type {string}
     * @memberof FieldsMapInnerInner
     */
    'date_format'?: FieldsMapInnerInnerDateFormatEnum;
    /**
     * Date fields only (text field formulas coming soon): formulas are a way to prefill fields with calculated future or past dates. Addition, subtraction, and parentheses are allowed. Valid event dates are `created_date`, `sent_date`, and `signed_date`. Valid time periods are `day`, `days`, `week`, `weeks`, `month`, and `months`. Example: `formula: \"sent_date + 10 days\"`. Use with `lock_sign_date` if you\'d like to make the field readonly and prevent signers from choosing a different date.
     * @type {string}
     * @memberof FieldsMapInnerInner
     */
    'formula'?: string;
}

type FieldsMapInnerInnerTypeEnum = 'initials' | 'signature' | 'checkbox' | 'date' | 'text' | 'autofill_company' | 'autofill_email' | 'autofill_first_name' | 'autofill_last_name' | 'autofill_name' | 'autofill_phone' | 'autofill_title' | 'autofill_date_signed'
type FieldsMapInnerInnerValidationEnum = 'no_text_validation' | 'numbers' | 'letters' | 'email_address' | 'us_phone_number' | 'us_zip_code' | 'us_ssn' | 'us_age' | 'alphanumeric' | 'us_bank_routing_number' | 'us_bank_account_number'
type FieldsMapInnerInnerDateFormatEnum = 'MM/DD/YYYY' | 'DD/MM/YYYY' | 'YYYY/MM/DD' | 'Month DD, YYYY' | 'MM/DD/YYYY hh:mm:ss a'


